Repository SunsetStation/SunsetStation, pull requests merged in 2018-10, with the labels that each got.

#162 Nerfs the blueshield
  sunset/code/game/objects/items/blueshield.dm
  sunset/code/modules/clothing/suits/blueshield.dm
  sunset/code/modules/jobs/job_type/blueshield.dm
  sunset/code/modules/projectiles/gun/blueshield.dm
  sunset/icons/obj/guns/energy.dmi
Labels: Balance/Rebalance, Removal

#210 Changes the engine floor sprites
  sunset/code/game/turfs/simulated/floor.dm
  sunset/icons/turf/floors.dmi
  sunsetstation.dme
Labels: Stale, Tweak

#378 Updates the Security map (Ready for Review)
  _maps/map_files/NSS-Sunset/NSS-Sunset.dmm
  sunset/code/game/area/Space_Station_13_areas.dm
Labels: Map Edit, Tweak

#478 new sm reactions
  code/modules/power/supermatter/supermatter.dm
Labels: Feature, Tweak
