Repository SunsetStation/SunsetStation, pull requests merged in 2018-09, with the labels that each got.

#64 Icy turfs
  code/__DEFINES/~sunset_defines/layers.dm
  sunset/code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  sunsetstation.dme
Labels: Feature

#72 Adds Give verb
  sunset/code/modules/mob/inventory.dm
  sunset/code/modules/mob/living/carbon/give.dm
  sunsetstation.dme
Labels: Feature

#87 Fixed manifest
  sunset/code/datums/sunsetbot.dm
Labels: Fix

#82 Add genpop
  _maps/map_files/NSS-Sunset/NSS-Sunset.dmm
  _maps/nss-sunset.dm
  _maps/nss-sunset.json
  code/__DEFINES/~sunset_defines/access.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/security.dm
  config/maps.txt
  goon/icons/obj/closet.dmi
  sunset/code/game/area/Space_Station_13_areas.dm
  sunset/code/game/machinery/turnstile.dm
  sunset/code/game/objects/items/cards_ids.dm
  sunset/code/game/objects/structures/crates_lockers/closets/secure/genpop.dm
  sunset/code/modules/jobs/access.dm
  sunset/icons/obj/turnstile.dmi
  sunsetstation.dme
  sunsetstation.lk
Labels: Config Update, Feature, Map Edit

#94 Adds admin freezing
  code/modules/admin/admin_verbs.dm
  sunset/code/modules/admin/verbs/randomverbs.dm
  sunset/code/modules/mob/mob_define.dm
  sunset/icons/effect/effects.dmi
  sunsetstation.dme
Labels: Feature

#99 Replaces bigtext loud mode on headsets with bold text
  code/modules/goonchat/browserassets/css/browserOutput.css
  interface/stylesheet.dm
  tmp/iconCache.sav
Labels: Tweak

#106 Retro computer resprites
  sunset/code/game/machinery/computer/buildandrepair.dm
  sunset/code/game/machinery/computer/computer.dm
  sunset/code/modules/modular_computers/computers/machinery/modular_console.dm
  sunset/icons/obj/computer.dmi
  sunset/icons/obj/modular_console.dmi
  sunset/icons/obj/stock_parts.dmi
  sunsetstation.dme
Labels: Sprites

#139 Adds a fancy title screen
  config/title_screens/LICENSE.txt
  config/title_screens/images/sunset.dmi
Labels: Config Update, Feature

#148 Port new meta toxins to NSS Sunset
  _maps/map_files/NSS-Sunset/NSS-Sunset.dmm
Labels: Map Edit

#127 Ports the blueshield
  code/__DEFINES/~sunset_defines/access.dm
  code/__DEFINES/~sunset_defines/jobs.dm
  code/controllers/subsystem/job.dm
  code/game/machinery/computer/card.dm
  code/modules/jobs/access.dm
  code/modules/jobs/jobs.dm
  icons/mob/hud.dmi
  sunset/code/game/area/Space_Station_13_areas.dm
  sunset/code/game/gamemodes/changeling/changeling.dm
  sunset/code/game/gamemodes/clock_cult/clock_cult.dm
  sunset/code/game/gamemodes/cult/cult.dm
  sunset/code/game/gamemodes/devil/devil_game_mode.dm
  sunset/code/game/gamemodes/overthrow/overthrow.dm
  sunset/code/game/gamemodes/revolution/revolution.dm
  sunset/code/game/gamemodes/traitor/traitor.dm
  sunset/code/game/objects/effects/landmarks.dm
  sunset/code/game/objects/items/blueshield.dm
  sunset/code/game/objects/items/devices/PDA/PDA_types.dm
  sunset/code/game/objects/items/devices/radio/encryptionkey.dm
  sunset/code/game/objects/items/devices/radio/headset.dm
  sunset/code/game/objects/structures/crates_lockers/closets/secure/blueshield.dm
  sunset/code/modules/clothing/suits/blueshield.dm
  sunset/code/modules/jobs/access.dm
  sunset/code/modules/jobs/job_type/blueshield.dm
  sunset/code/modules/jobs/job_type/job.dm
  sunset/code/modules/jobs/job_type/job_override.dm
  sunset/code/modules/projectiles/gun/blueshield.dm
  sunset/icons/mob/suit.dmi
  sunset/icons/mob/uniform.dmi
  sunset/icons/obj/ammo.dmi
  sunset/icons/obj/closet.dmi
  sunset/icons/obj/clothing/suits.dmi
  sunset/icons/obj/clothing/uniform.dmi
  sunset/icons/obj/guns/energy.dmi
  sunset/icons/obj/guns/projectile.dmi
  sunset/icons/obj/storage.dmi
  sunsetstation.dme
Labels: Feature, Sprites, in progress

#158 HEAT-LAMP SYNDROME
  sunset/code/datums/diseases/transformation.dm
  sunsetstation.dme
Labels: Feature

#174 [MIRROR] the correct plasma cutter balance change
  code/modules/projectiles/projectile/special/plasma.dm
Labels: Balance/Rebalance

#173 [MIRROR] Fixes plasma cutters not using charge when used as welder, and adds flashing
  code/modules/projectiles/guns/energy/special.dm
Labels: Balance/Rebalance, Fix

#183 Upstream merge
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/~sunset_defines/atom_hud.dm
  code/datums/forced_movement.dm
  code/datums/hud.dm
  code/game/gamemodes/hivemind/hivemind.dm
  code/game/gamemodes/hivemind/objectives.dm
  code/game/machinery/quantum_pad.dm
  code/game/objects/items/devices/quantum_keycard.dm
  code/game/objects/items/implants/implant_mindshield.dm
  code/game/turfs/open.dm
  code/modules/antagonists/hivemind/hivemind.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/spells/spell_types/hivemind.dm
  code/modules/vending/sustenance.dm
  html/changelogs/AutoChangeLog-pr-40245.yml
  html/changelogs/AutoChangeLog-pr-40296.yml
  html/changelogs/AutoChangeLog-pr-40411.yml
  html/changelogs/AutoChangeLog-pr-40423.yml
  html/changelogs/AutoChangeLog-pr-40431.yml
  html/changelogs/AutoChangeLog-pr-40449.yml
  html/changelogs/AutoChangeLog-pr-40452.yml
  icons/mob/actions/actions_hive.dmi
  icons/mob/actions/backgrounds.dmi
  icons/mob/hud.dmi
  icons/obj/device.dmi
  sunset/icons/mob/hud.dmi
  sunsetstation.dme
  tgstation.dme
Labels: Map Edit, Sprites

#172 Retro sprites
  sunset/code/game/machinery/limbgrower.dm
  sunset/code/game/machinery/newscaster.dm
  sunset/code/game/machinery/requests_console.dm
  sunset/code/game/machinery/telecomms/machines/message_server.dm
  sunset/code/modules/mining/machine_stacking.dm
  sunset/icons/obj/machines/limbgrower.dmi
  sunset/icons/obj/stationobjs.dmi
  sunset/icons/obj/terminals.dmi
  sunsetstation.dme
Labels: Sprites, Tweak, Work in progresss

#140 resprites for rnd and some servers
  sunset/code/game/machinery/telecomms/machines/message_server.dm
  sunset/code/modules/research/destructive_analyzer.dm
  sunset/code/modules/research/rdmachines.dm
  sunset/code/modules/research/server.dm
  sunset/icons/obj/machines/research.dmi
  sunsetstation.dme
Labels: Work in progresss

#118 Vending machine ui
  code/modules/vending/_vending.dm
  sunset/code/modules/vending/_vending.dm
  sunsetstation.dme
Labels: Tweak, UI, Work in progresss

#169 fixes tile movement
  config/game_options.txt
  sunset/code/World.dm
  sunset/code/modules/client/preferences.dm
  sunsetstation.dme
Labels: Config Update, Fix

#235 Vox
  code/modules/mob/living/carbon/human/species.dm
  sunset/code/modules/mob/living/carbon/human/species.dm
  sunsetstation.dme
Labels: Config Update, Fix, Sprites
